### PR TITLE
Open Crowd Fund

### PR DESCRIPTION
**Pull request by rwieruch**
Hey, I built this neat little open source project to take full control over your own crowd funding campaigns. Not sure if you want to add it, but I thought it might be a good addition :)

### CODE REVIEW

**Comment by shime** [comment]
Hey! Looks good, does it have a landing page?

**Comment by rwieruch** [comment]
It's only a GitHub repository with a Demo Crowdfunding Campaign. So no big product at all, but enables people to do their own crowdfunding via their own Stripe account to receive payments.

**Comment by shime** [comment]
"No big product at all" is a plus, but I would prefer if it had a nice landing page we can link to.

**Comment by rwieruch** [comment]
Sorry that there is none. It was just a by-product as I needed a platform to do my own crowdfunding campaign. It works, but I don't intend to build more around it. Really up to you if you want to include it. I just saw you post on HN and though I would do a quick PR and see if you would want to add it, because I liked the idea of this repository :) I hope it grows even more in the future. Best wishes!

**Comment by shime** [comment]
Thank you for proposing it! No hard feelings, I hope. Best wishes to you too!

**Comment by rwieruch** [comment]
No worries :)

**Pull request closed without merging**
