### PR TITLE
add ntfy

### PR DESCRIPTION
**Pull request by dschep**
Adding ntfy, a small side project of mine to bring notifications to your command line. It supports Linux/Windows/macOS and their respective desktop notification systems as well as pushover, pushbullet, simplepush, xmpp, and a ton of other push notification services.

### CODE REVIEW

**Comment by shime** [comment]
Awesome, thanks!

**Comment by shime** [comment]
Actually I'm gonna remove it because it's a Python library and not a product. Sorry, but I have to draw a line somewhere.

**Comment by dschep** [comment]
It's written in Python meant for use at the command line. It _can_ be used as a library but that's mostly un-supported :wink:

**Comment by shime** [comment]
It's a CLI tool, not a product.

Maybe submit it to:
* https://github.com/agarrharr/awesome-cli-apps
* https://github.com/alebcay/awesome-shell
* https://github.com/Kikobeats/awesome-cli

Sorry.

**Comment by millette** [comment]
Perhaps update your readme too, if you don't consider command-line applications. I for one love my clis!

**Comment by dschep** [comment]
It's your list so manage it as you please. But, out of curiosity, how are you defining "product?"

Are any of these products?
* http://dschep.github.io/GistMarklets/
* https://github.com/dschep/proven
* http://dschep.github.io/imgur-album-downloader/#/
* https://share.bikehero.io/

Are you just requiring a GUI?

**Comment by shime** [comment]
Yeah, I have to be more specific.

But, https://share.bikehero.io looks like a product to me.

**Comment by dschep** [comment]
Coolio. From the look of the current products, you're also looking for a high level of polish, both in the application & marketing, might be worth noting that too if it's part of your criteria (and it's highly subjective, allowing you to pick an choose without anyone really getting to complain :grin:)

**Comment by shime** [comment]
Well, to be fair, the list is named "awesome". 😁

**Pull request merged**
